In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
my_df = pd.DataFrame({"A" : [1,4,7,10,13],
                     "B" : [3,6,9,np.nan,15],
                     "C" : [2,5,np.nan,11,np.nan]})

In [3]:
#Need to instantiate
imputer = SimpleImputer()
#An object is created as imputer

In [4]:
#Fit #Need to calculate values it needs to impute - mean value of each column
imputer.fit(my_df) #Want it to learn from my_df
#May need same imputation logic again - we want to keep from training data




SimpleImputer()

In [5]:
#Transform #Apply logic onto data
imputer.transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [6]:
#Returned an array representing each column in data frome
#Replaced missing values with mean from each column
#Just printed to console

my_df1 = imputer.transform(my_df) #Now data is stored

In [7]:
#We can run fit_transform that does both
imputer.fit_transform(my_df) #Only use on training data

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [8]:
#Use fit and transform separately for test data
#We want imputation rules based off of training data
#If we run on both, we'll have different imputation outputs
#and our assumptions on how model will perform in real world will be flawed

In [9]:
#Put array back into data from
my_df2 = pd.DataFrame(imputer.fit_transform(my_df), columns = my_df.columns)

In [10]:
my_df2

A      B     C
0   1.0   3.00   2.0
1   4.0   6.00   5.0
2   7.0   9.00   6.0
3  10.0   8.25  11.0
4  13.0  15.00   6.0

In [12]:
#Learn rules based on column B
#Apply imputation to one or select columns
imputer.fit_transform(my_df[["B"]])

array([[ 3.  ],
       [ 6.  ],
       [ 9.  ],
       [ 8.25],
       [15.  ]])

In [13]:
#Apply and over write original with new
my_df["B"] = imputer.fit_transform(my_df[["B"]])

In [14]:
my_df
#Column B is updated, column C is not

A      B     C
0   1   3.00   2.0
1   4   6.00   5.0
2   7   9.00   NaN
3  10   8.25  11.0
4  13  15.00   NaN